"""create budgets table

Revision ID: 0001_budgets
Revises:
Create Date: 2026-07-07

First migration. Hand-written (rather than autogenerated) so it stays
portable across Postgres and SQLite: string status column, no DB enum,
CURRENT_TIMESTAMP default.
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "0001_budgets"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "budgets",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False, server_default="inactive"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("CURRENT_TIMESTAMP"),
        ),
    )


def downgrade() -> None:
    op.drop_table("budgets")
